# Generated by Django 2.2.4 on 2020-02-09 23:31

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='buyer',
        ),
        migrations.AddField(
            model_name='group',
            name='winner',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
