# Generated by Django 2.2.4 on 2020-02-10 00:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebay', '0002_auto_20200209_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='auctionenddate',
        ),
        migrations.RemoveField(
            model_name='group',
            name='auctionstartdate',
        ),
        migrations.AddField(
            model_name='group',
            name='auction_end_date',
            field=otree.db.models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='auction_start_date',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
